### PR TITLE
Consolidate linting and compliance

### PR DESCRIPTION
**Pull request by silverbucket**
Moves the existing sockethub `.eslintrc` file to the root directory, so it applies to all modules instead of just one.

### CODE REVIEW

**Comment by silverbucket** [comment]
Weird error with codeclimate `Parsing error: parser.parse is not a function` 
https://github.com/gilbarbara/codeclimate-stylelint/issues/33#issuecomment-778470025

**Comment by raucao** [comment]
It would be useful to keep unrelated changes out of PRs, but especially to keep unrelated changes out of single commits!

**Review by raucao — APPROVED** [review]
:+1:

**Comment by silverbucket** [comment]
Ended up being a lot more work debugging travis and making sure all packages tests are run as expected, putting it back up for review as a lot more commits were made since @raucao approved a few days ago.

**Review by raucao — APPROVED** [review]
:+1:

**Pull request merged**
