### PR TITLE
Fix/update Docker setup

### LINKED ISSUE #511: Couple issues with docker-compose setup
Just tried setting up with `docker-compose` and I ran into the following issues:

* No `version` in `docker-compose.yml` so I had to add one (giving me parsing errors)
* Changed `links` to `networks` (not sure if this was actually needed in the end)
* Had to change `Dockerfile` entrypoint and config copy path to different path because of `ADD . /app` and the current lerna-based repo design.
* Rearranged the Dockerfile so that it uses lerna now (so that it uses the local version of the platforms, otherwise it pulls from npm which is old and throws errors)
* Added `depends_on` to wait for redis to start

Here's the final files

docker-compose.yml
```yml
version: "3.6"
services:
  sockethub:
    build: .
    ports:
      - "10550:10550"
    networks:
      - sockethub-net
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - sockethub-net

networks:
  sockethub-net:

```

Dockerfile
```Dockerfile
FROM node:16
MAINTAINER Ben Kero <ben.kero@gmail.com>

RUN mkdir -p /app
WORKDIR /app
ADD . /app

RUN npm install
RUN npx lerna bootstrap
RUN npx lerna run build

ADD packages/sockethub/config.json.example /app/packages/sockethub/config.json

EXPOSE 10550
CMD DEBUG=sockethub* /app/packages/sockethub/bin/sockethub --examples --host 0.0.0.0

```

I'll loop back and make a PR if these changes seem sane to the maintainers

### PR DESCRIPTION
**Pull request by Cobertos**
~~Not completed yet, need to rewrite the parts that I wrote with yarn still~~
Should be good now

closes #511

### CODE REVIEW

**Comment by Cobertos** [comment]
image
Looks to be working now with yarn

I didn't do any build size optimization for this. Let me know if that's needed.

**Comment by silverbucket** [comment]
Thanks @Cobertos, this LGTM! 

> I didn't do any build size optimization for this. Let me know if that's needed.

I don't think it's anything to worry about for now, we can always optimize later.

**Review by silverbucket — APPROVED** [review]

**Comment by silverbucket** [comment]
BTW @Cobertos  - @raucao added your account to our kredits ecosystem for contributors, so you can receive kredits! 

All PRs take a `kredits-*` label (`kredits-1` for minor, `kredits-2` for medium, `kredits-3` for an insane amount of work) which will be tied to the assignee of the PR. Reviewers also get a smaller fraction of kredits in relation to the label. 

You can check it out at https://kredits.kosmos.org/dashboard and read more about Kredits at https://wiki.kosmos.org/Kredits ... feel free to let us know if you have any questions or comments.

**Comment by Cobertos** [comment]
I ended up switching to Matrix for the client work I was working on (instead of IRC) so ended up switching off Sockethub.

But thanks for the add!

**Pull request merged**
