### PR TITLE
Update docker files

### PR DESCRIPTION
**Pull request by silverbucket**

### CODE REVIEW

**Comment by raucao** [comment]
The CI actually failed for this one...

**Comment by silverbucket** [comment]
@raucao I don't think so... https://www.travis-ci.com/github/sockethub/sockethub/builds/223746156

**Comment by raucao** [comment]
https://github.com/sockethub/sockethub/runs/2400760782

**Comment by silverbucket** [comment]
@raucao  seems this new dependency management bot is force-pushing in their PRs which causes problems in the CI finding the ref in git. :/

**Comment by silverbucket** [comment]
Oh wait, then why would it be happening here? I think I'm confusing two different issues. My previous comment is valid for the other PRs that have come in today, but not this one. This one is likely due to https://github.com/sockethub/sockethub/pull/373

**Comment by raucao** [comment]
> seems this new dependency management bot is force-pushing in their PRs

That's a terrible thing to do.

**Comment by silverbucket** [comment]
> > seems this new dependency management bot is force-pushing in their PRs
> 
> That's a terrible thing to do.

Yeah a lot of weird things going on with the CI now. Not so happy with this bot may look for another solution

**Pull request merged**
