### PR TITLE
Allow for permissive '@id` ID in ActivityStreams objects, rather than enforcing URIs like the old way

### PR DESCRIPTION
**Pull request by silverbucket**
Most of the actual code for this is in dependency packages, but examples were updated and some tests were added here.

### CODE REVIEW

**Comment by skddc** [comment]
Even if @gregkare knows what this is about, it would still be good to have a proper title and description, so that everyone knows what changed. Especially when it's appearing on the Kredits dashboard.

**Comment by silverbucket** [comment]
@skddc github cuts branch names after `_` apparently, but anyway I updated the title and description.

**Comment by skddc** [comment]
> Most of the actual code for this is in dependency packages, but examples were updated and some tests were added here.

Then this PR should actually explain those changes, not what happened elsewhere. Something along these lines e.g..:

> Update dependencies, add example and tests for ID validation

**Comment by silverbucket** [comment]
@gregkare I reviewed the code (fixed some unrelated minor issues) but could not replicate your problem. I'm guessing this is an `npm link` issue. Please make sure you have links set up for the following repos (and have them checked out with their respective branches for this PR)

* sockethub `feature/permissive_id`
```
$ find node_modules/ -maxdepth 1 -type l -ls
4329107675        0 lrwxr-xr-x    1 njenning         600                    68 Oct 16 22:50 node_modules//sockethub-platform-xmpp -> ../../../../../../usr/local/lib/node_modules/sockethub-platform-xmpp
4329107710        0 lrwxr-xr-x    1 njenning         600                    51 Oct 16 22:50 node_modules//irc2as -> ../../../../../../usr/local/lib/node_modules/irc2as
4327669991        0 lrwxr-xr-x    1 njenning         600                    67 Oct  9 16:47 node_modules//sockethub-platform-irc -> ../../../../../../usr/local/lib/node_modules/sockethub-platform-irc
```

* sockethub-platform-irc `feature/permissive_id`
```
$ find node_modules/ -maxdepth 1 -type l -ls
4329113958        0 lrwxr-xr-x    1 njenning         600                    51 Oct 16 23:34 node_modules//irc2as -> ../../../../../../usr/local/lib/node_modules/irc2as
```

* irc2as `feature/channel_modes_groups`

* sockethub-platform-xmpp `feature/permissive_id`

**Comment by gregkare** [comment]
I was using npm link wrong. I changed the version numbers for the unreleased dependencies to the last release on npm (the easy way is to run `npm install irc2as --save-prod-dev` so you don't have to know what the latest version is), then npm linked everything again. I'm going to review the new changes and test the examples locally

**Comment by silverbucket** [comment]
@gregkare - I double checked this and first thought I also encountered the same error, but then realized I was on a different branch. When I switched back to this branch I was able to connect without issue. Can you please double check you have the right branches and links? I can't think of any other variable we could be missing.

**Pull request merged**
