### PR TITLE
Refactor sockethub-client

### PR DESCRIPTION
**Pull request by silverbucket**
Refactored SockethubClient
 - socket.io emit callbacks now supported
 - TypeScript
 - Updated connect events to match socket.io v3
 - Bundle ASFactory
 - Using tsc + webpack with minified and unminified output with source maps
 - Bugfixes related to replay and event handling
 - Refactored middleware

**TODO** Update examples

### CODE REVIEW

**Comment by silverbucket** [comment]
@raucao @galfert As mentioned during our call a few weeks ago, this is a huge PR, that I'd already had one pass at to split up, but the refactor is just too big to reasonably split things up into smaller PRs (and would take a lot longer to attempt for the second time). However this PR has unit tests, the examples work, and I even started a non-working PR for hyperchannel to use this branch, however I just don't know enough about the way the code works to get it to fully work. More on that here: https://github.com/67P/hyperchannel/pull/270

This PR is ready for review! The sooner we can merge it the sooner I can try to tackle a few more related breaking changes that I didn't want to include in this branch. I can start to branch new PRs from this branch, but would like at least some preliminary reviews first so we don't miss anything big.

**Comment by raucao** [comment]
Shall we have a look at it together today?

**Comment by silverbucket** [comment]
@raucao I have been pretty sick, so maybe we can pair in another day or two, however if anyone has time to do an independent check on the PR it would be helpful to try to catch things I missed. @galfert ?

**Review by raucao — APPROVED** [review]
This works very well with the respective Hyperchannel branch now. The client code over there is much cleaner with the new callback API. Changes here LGTM. Great job! :clap:

**Pull request merged**
