### PR TITLE
Fix the Dockerfile

### PR DESCRIPTION
**Pull request by gregkare**
The trusty tag was removed from npm's Docker repository, the current
Dockerfile doesn't work anymore

Use the current LTS instead (4.6.0)

### CODE REVIEW

**Comment by gregkare** [comment]
I'm getting the same error as on Travis (https://travis-ci.org/sockethub/sockethub/jobs/167709001) on my local machine when running the tests:

```

> sockethub@1.0.3 test /Users/kare/code/kosmos/sockethub
> jaribu

jaribu is in: /Users/kare/code/kosmos/sockethub/node_modules/jaribu/bin/../
app is in: /Users/kare/code/kosmos/sockethub/node_modules/jaribu/bin/../../../
[ '/Users/kare/code/kosmos/sockethub/test/init-suite.js',
  '/Users/kare/code/kosmos/sockethub/test/schema-suite.js',
  '/Users/kare/code/kosmos/sockethub/test/validate-suite.js' ]

/Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:2604
                    throw err;
                    ^

Error: Tried loading "/Users/kare/code/kosmos/sockethub/lib/validate" at /Users/kare/code/kosmos/sockethub/lib/validate then tried node's require("/Users/kare/code/kosmos/sockethub/test/./../lib/validate") and it failed with error: TypeError: Cannot read property 'length' of undefined
    at /Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:2597:27
    at Object.execCb (/Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:1943:33)
    at Object.check (/Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:1131:51)
    at Object.enable (/Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:1423:22)
    at Object.init (/Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:1036:26)
    at callGetModule (/Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:1450:63)
    at Object.completeLoad (/Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:1837:21)
    at Function.req.load (/Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:2610:17)
    at Object.load (/Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:1932:21)
    at Object.load (/Users/kare/code/kosmos/sockethub/node_modules/requirejs/bin/r.js:1082:29)
npm ERR! Test failed.  See above for more details.
```

Checking if updating requirejs fixes it

**Comment by gregkare** [comment]
The current jaribu depends on "requirejs": "^2.3.2".

@silverbucket any idea what's going on there? The `validate` script doesn't like something about requirejs's code

**Comment by silverbucket** [comment]
@gregkare just switched the order of the nconf files and the tests pass on my computer, so im reading up on nconf (it's been a while) to see what's going on.

**Comment by gregkare** [comment]
Thanks! I didn't expect that based on the error, tests run and pass on my laptop too without  	274ca29

**Comment by silverbucket** [comment]
works now!

**Comment by gregkare** [comment]
Thanks!

**Pull request merged**
