### PR TITLE
Use ISO 8601 dates for incoming XMPP messages

### LINKED ISSUE #247: Format of published field changed
In the latest Sockethub release (3.1.2), the message's `published` field format changed from being an ISO 8601 datetime string (e.g. "2019-06-14T06:32:42.025Z") to a unix timestamp string (e.g. "1577981398164").

Was this on purpose or did it happen by accident? I couldn't find anything about it in the release notes or the documentation.

### PR DESCRIPTION
**Pull request by silverbucket**
Set the `published` property to `ISO 8601`.
Resolves #247

### CODE REVIEW

**Comment by raucao** [comment]
What about #691? I already implemented this, and the tests should be red in a commit, before reviewing the functionality.

**Comment by silverbucket** [comment]
@raucao this is ready for review, based on your previous PR and added schema support for the `date-time` format.

**Comment by raucao** [comment]
My previous PR shows a testing bug where the schema isn't validated in the tests, which hasn't been fixed in that branch. You can push to the same branch to prove that the tests are actually validating the schema correctly, but it should be a different branch to fix that I think.

**Comment by raucao** [comment]
> I'm sorry but I don't understand exactly what you are saying should be done, or what's wrong with this PR.

I'm saying there's no way for me to know that the validation is actually being applied now, other than jumping into the code myself. A PR that fixes the validations being applied would have a test that shows that they are applied. Same if it would just be a commit that uses my intentionally faulty schema.

It's just that since I had everything prepared in the other PR for exactly that, and the PR is still open, it wasn't obvious that you actually fixed the validations. And it's still not clear to me, because there's no commit message stating that, or reference to the PR that proved they were broken.

I'll just jump into the code and verify it manually be editing it again then.

**Comment by raucao** [comment]
I checked, and the same bug for the tests still persists. They are green, despite the format not matching the schema.

I have pushed a similar commit to this branch to demonstrate the bug.

**Comment by silverbucket** [comment]
@raucao Sorry for taking so long to get to this, summer break :) .. I finally figured out what was so confusing about this issue. The `published` field was being defined on an `ActivityObject` and no the base `ActivityStream`. This should be working 100% now.

**Comment by silverbucket** [comment]
@raucao spoke too soon, coverage seems to be failing on github, though it's passing locally.

**Comment by silverbucket** [comment]
@raucao OK, test added to schemas to bring coverage back up to 95%

**Review by raucao — APPROVED** [review]
:+1: :rocket:

**Pull request merged**
