### PR TITLE
Switch to Mocha

### PR DESCRIPTION
**Pull request by silverbucket**
Switch to mocha from jest, as jest tests are causing problems with integration testing (being developed in a different branch)

### CODE REVIEW

**Comment by silverbucket** [comment]
@galfert and @raucao this PR is ready for review, took a lot of time to work through this, lots of sticky parts that operate totally differently in jest that had to be resolved, but it all looks good now.

**Review by galfert — APPROVED** [review]
Changes look good to me and all tests are green. Have to admit though that I haven't read every single line in detail, because it's quite a lot of changes :)

**Comment by silverbucket** [comment]
Thanks @galfert !

**Comment by FawadAkhtar110** [comment]
@fawadakhtar110

**Pull request merged**
