### PR TITLE
Use `postinstall` for `lerna bootstrap`

### PR DESCRIPTION
**Pull request by silverbucket**
* Use `postinstall` for `lerna bootstrap`
* Update github actions and docker
* Update docs for a more conventional quick start

### CODE REVIEW

**Review by raucao — COMMENTED** [review]
I tried a fresh checkout, and cannot `yarn run dev` immediately after `yarn install` and `yarn run build && yarn test` (both green). It's missing a default config file it seems:

> Error: Config file not found: sockethub.config.json

**Comment by silverbucket** [comment]
@raucao It seems to have have something to do with the build not fully executing (even though it's a dependency for the run directive), I added another build step to the `postinstall` directive, with caching disabled. It seems to be working for me, can you see how it goes for you?

**Comment by silverbucket** [comment]
eg. this command succeeded for me: 
`git clone git@github.com:sockethub/sockethub.git && cd sockethub && git co td/quick-start && yarn install && yarn run dev`

**Comment by raucao** [comment]
Now it works, but it feels kind of wrong to build everything in the install command, which is only supposed to pull dependencies. If you say this should happen in the `dev` command, then wouldn't it be better to do it there?

**Review by raucao — APPROVED** [review]
:+1:

**Pull request merged**
