### PR TITLE
add release drafter

### PR DESCRIPTION
**Pull request by silverbucket**

### CODE REVIEW

**Comment by raucao** [comment]
Just a heads up: one quirk of release drafter is that before you've created your first release with it, it will keep updating the first draft with *all* closed PRs in the repo's history (at least the last few times I set it up). So, just wait with removing the extra entries, until you actually want to release...

**Comment by silverbucket** [comment]
@raucao good to know, but is there still something I need to do? When I go to releases there's no draft there.

**Comment by raucao** [comment]
If you installed the GitHub app for the repo and added the yml file, then the draft will appear eventually.

**Comment by silverbucket** [comment]
@raucao hmm, still nothing. It exists in settings->integrations though. https://github.com/organizations/sockethub/settings/installations/13081122

**Comment by raucao** [comment]
Maybe as them directly then: https://github.com/release-drafter/release-drafter

**Pull request merged**
