### PR TITLE
Use `lerna-lite` to publish

### LINKED ISSUE #743: Switch to yarn workspaces and lerna-lite?
Evaluate removing lerna entirely, using something like `yarn workspaces` for linking local dependencies, and `lerna-lite` for version management and publishing.
https://classic.yarnpkg.com/lang/en/docs/workspaces/
https://github.com/ghiscoding/lerna-lite

### PR DESCRIPTION
**Pull request by silverbucket**
`pnpm publish` behaves a lot differently than `lerna publish` did and I really liked that feature of lerna so we can use `lerna-lite` just for the publishing.

Resolves #743

### CODE REVIEW

**Review by raucao — APPROVED** [review]
thumbs-up-boy

**Comment by silverbucket** [comment]
Cheers, this PR will need to wait for #678  before it can be merged.

**Comment by ghiscoding** [comment]
@silverbucket 
you should think about adding `publish` package as well to your `package.json` in order to be ready for Lerna-Lite v2.0 since as I mentioned to you in Lerna-Lite, `publish` and `version` are becoming optional in v2.0

```diff
"devDependencies": {
    "@lerna-lite/cli": "1.17.0",
+   "@lerna-lite/publish": "1.17.0", 
```

**Comment by silverbucket** [comment]
Right, thanks for the heads up @ghiscoding will do that now.

**Pull request merged**
