### PR TITLE
Support incoming message correction for XMPP messages

### PR DESCRIPTION
**Pull request by raucao**
* Uses the message ID as default, and adds the stanza ID in a separate, new property
* Adds another new property for message correction/replacement as per XEP-0308

This introduces a breaking change (albeit only for clients who already cache/store messages by ID), in that the main message "id" for XMPP messages has been changed from using the stanza ID to using the message's "id" attribute value. The stanza ID is now a separate property, as it is also needed (for example for MAM).

### CODE REVIEW

**Comment by galfert** [comment]
Can confirm that it works with Hyperchannel. But I see warnings in the console:

> activity-streams.min.js:2 invalid property: "xmpp:stanza-id"

Looks like the necessary changes to the schema are missing here.

**Comment by silverbucket** [comment]
> But I see warnings in the console:
> 
> > activity-streams.min.js:2 invalid property: "xmpp:stanza-id"
> 
> Looks like the necessary changes to the schema are missing here.

Yeah this property should be added to `activity-streams.js`. That library may be totally removed eventually but for now best to keep it up to date. Otherwise this looks good to me.

**Comment by raucao** [comment]
I just had a look at adding the properties to the validation. However, I don't want to add specific properties, but only the namespace, so that any properties in the namespace are valid. However, in order to do that correctly, we also need to set `@context`, and so this is quickly adding new features to `activity-streams.js` which shouldn't really be in there, because they are not specific to AS.

> That library may be totally removed eventually

If this is already the rough plan, then maybe now would be a good time? We're going to break the AS format anyway in the next release.

**Comment by silverbucket** [comment]
> > That library may be totally removed eventually
> 
> If this is already the rough plan, then maybe now would be a good time? We're going to break the AS format anyway in the next release.

Something still needs to be done to replace a portion of the functionality it provides (expanding AS objects that are referenced just by ID), so it's not ready to be completely removed yet, but I do plan to remove it as part of the breaking release. So then lets just leave it as-is with the warning, for now.

**Review by silverbucket — APPROVED** [review]

**Pull request merged**
